### ISSUE TITLE
JS SDK v1

### ISSUE THREAD

**Issue by gao-sun** [logto-io/js#15]
## Summary
第一个可用版本。

## Deliverables
- [ ] logto-io/token-validator#14
- [ ] logto-io/token-validator#13
- [x] logto-io/token-validator#11
